### ISSUE TITLE
Flag domain_error

### ISSUE THREAD

**Issue by Erhannis** [jiprolog/jiprolog#18]
According to my very limited understanding of Prolog flags, the following should work (i.e., `test(A)` should have one solution, A = 1, and then there should be no more solutions) :

```
:- create_prolog_flag(test_flag, true, []).

test(A) :-
  current_prolog_flag(test_flag, true),
  A = 1
  .
```

But instead, while I do get the one solution I expect, I then get an error, like so:

```
Exception in thread "main" com.ugos.jiprolog.engine.JIPRuntimeException: error(domain_error(prolog_flag,test_flag),context(error(domain_error(prolog_flag,test_flag)),file(undefined,0)))
	at com.ugos.jiprolog.engine.H.unify(Error1.java:35)
	at com.ugos.jiprolog.engine.i.a(BuiltIn.java:38)
	at com.ugos.jiprolog.engine.BuiltInPredicate.a(BuiltInPredicate.java:79)
	at com.ugos.jiprolog.engine.PrologObject.b(PrologObject.java:84)
	at com.ugos.jiprolog.engine.aX.a(WAM.java:413)
	at com.ugos.jiprolog.engine.aX.b(WAM.java:179)
	at com.ugos.jiprolog.engine.JIPQuery.nextSolution(JIPQuery.java:84)
	at jiptest.Main.main(Main.java:46)
```

Am I doing something wrong?  It seems like incorrect behavior to throw an error, here.

JIProlog 4.1.6.1

**Comment by pmoura** [comment]
`create_prolog_flag/2` is not a standard Prolog predicate.

**Comment by pmoura** [comment]
The bug in the definition of the `current_prolog_flag/2`. It must check first if the flag name is valid before accessing its value but instead is doing it after returning the flag value.
